number 21 GET /api/users
Dantren18/davids-first-project pull request #6
Opened 2022-02-17 12:25 UTC by Dantren18

2022-02-17 14:17 UTC, douglashellowell commented on __tests__/app.test.js
> +            expect(articles[0]).toEqual({
Ideally your single-article wouldn't be sent back as the only item in an array

You should send back an object, not an array

2022-02-17 14:18 UTC, douglashellowell commented on __tests__/app.test.js
> +            expect(typeof articles[0]).toEqual("object");
These tests are a bit redundant.

your `toEqual` test is already testing these things

2022-02-17 14:20 UTC, douglashellowell commented on __tests__/app.test.js
> +  describe.only("GET /api/users", () => {
please remove `.only` before commiting!

2022-02-17 14:22 UTC, douglashellowell commented on __tests__/app.test.js
> +    test("Status 200: response to be an array of objects of length 3", () => {
the tests on `218`, `229` and `243` are all testing similar things - you can speed up your tests by making one request and making these assertions on the same response

2022-02-17 14:24 UTC, douglashellowell commented on controllers/controllers.js
> +exports.getTopicsController = (req, res, next) => {
You don't need to add the word `Controller` or `Model` to the function names (though if you want to keep it this way that's okay (other tutors may disagree))

2022-02-17 14:26 UTC, douglashellowell commented on models/models.js
> +    .query(`SELECT * FROM articles WHERE article_id = $1`, [article_id])
I'm confused about what this query is doing?

you aren't using the result of it

You don't need to make multiple queries here
your `UPDATE` query is enough

2022-02-17 14:32 UTC, douglashellowell commented on controllers/controllers.js
> +      const article = articles.find(
why are you needing this `.find` here?

any data filtering/manipulation should be done in your model - and your model aready has a `WHERE` clause so the filtering should already be done

2022-02-17 14:36 UTC, douglashellowell requested changes
looking good!

There is some unnecessary code in your model and controller (see my other comments)

you need to remove the `.only` from your tests before commiting again

2022-02-17 14:59 UTC, Dantren18 commented on controllers/controllers.js
> +exports.getTopicsController = (req, res, next) => {
Oh okay, I thought it helped made it easier to differentiate between the 2, I was finding it hard to think of appropriate different names for them otherwise!

2022-02-17 15:12 UTC, Dantren18 commented on __tests__/app.test.js
> -    test("Item should have correct keys", () => {
Hmm I cant figure out what endpoint test that was for now, but I have a test for that on the api/users already

2022-02-17 15:14 UTC, Dantren18 commented on __tests__/app.test.js
> +            expect(typeof articles[0]).toEqual("object");
Yes I see, removed them

2022-02-17 15:29 UTC, Dantren18 commented on __tests__/app.test.js
> +            expect(articles[0]).toEqual({
Made the change :)

2022-02-17 16:08 UTC, Dantren18 commented on models/models.js
> +    .query(`SELECT * FROM articles WHERE article_id = $1`, [article_id])
Corrected

2022-02-17 16:09 UTC, Dantren18 commented on controllers/controllers.js
> +      const article = articles.find(
Corrected

2022-02-18 09:58 UTC, popatre requested changes

2022-02-18 09:58 UTC, popatre commented on __tests__/app.test.js
> +    test("422 - inc_vote property not included in request body", () => {
- [ ] I would change these to error 400 - bad request

2022-02-18 09:58 UTC, popatre commented on __tests__/app.test.js
> +        .send({ inc_votes: "dog" })
The title for the test below seems more relevant to this test. 
The one below doesnt actually patch anything, there is no send. 
I'd change this title, then do a test for it the inc_votes is just an empty string - if you're wanting these two tests

2022-02-18 09:58 UTC, popatre commented on __tests__/app.test.js
> +        .send({ inc_votes: 0, favouritePet: "dogs" })
This doesnt really check if its 200, as you've incremented by 0. 
I'd either 200 - increments and ignores the extra property, or 400 - bad request, (too many keys on the object).

2022-02-18 09:58 UTC, popatre commented on __tests__/app.test.js
>          });
- [ ] TEST - what if the key is spelt wrong e.g. {inc_votessss: 100}

2022-02-18 09:58 UTC, popatre commented on controllers/controllers.js
> +exports.getTopicsController = (req, res, next) => {
Im cool with it

2022-02-18 11:39 UTC, Dantren18 commented on __tests__/app.test.js
> +    test("422 - inc_vote property not included in request body", () => {
Done

2022-02-18 11:43 UTC, Dantren18 commented on __tests__/app.test.js
> +        .send({ inc_votes: "dog" })
Yeah not sure what happened with my second test! made the change thanks

2022-02-18 14:08 UTC, popatre approved these changes

2022-02-18 14:34 UTC, merged