9 get articles
Dantren18/davids-first-project pull request #7
Opened 2022-02-18 10:56 UTC by Dantren18

2022-02-18 10:57 UTC, Dantren18 commented
Please note that my tests are failing here:

![image](https://user-images.githubusercontent.com/97050446/154669905-afcacfe8-a227-4c6e-98a5-2763ed1b03e8.png)

This is for a previous endpoint which I had working but when I changed branches it lost the progress. So when I merge I will combine the two.

2022-02-18 12:14 UTC, popatre requested changes

2022-02-18 12:14 UTC, popatre commented on __tests__/app.test.js
> +const { expect } = require("@jest/globals");
Not sure tou need this - it looks like an auto-import

2022-02-18 12:14 UTC, popatre commented on __tests__/app.test.js
> +        .send({ inc_votes: 0, favouritePet: "dogs" })
- [ ] TEST - patch to an valid article id, but the article doesnt exist e.g.  .patch("/api/articles/500000"
- [ ] TEST - patch to an invalid article id e.g.  .patch("/api/articles/sausages"

2022-02-18 12:14 UTC, popatre commented on models/models.js
> +      return db.query(
If the article id is 900000, it will still get into the then with an empty array - what happens then?

Need to refactor this.

2022-02-18 12:23 UTC, Dantren18 commented on __tests__/app.test.js
> +const { expect } = require("@jest/globals");
yep no idea when / how that for there! Deleted it

2022-02-18 15:46 UTC, Dantren18 commented on __tests__/app.test.js
> +        .send({ inc_votes: 0, favouritePet: "dogs" })
added

2022-02-18 15:46 UTC, Dantren18 commented on models/models.js
> +      return db.query(
covered in above test

2022-02-19 18:45 UTC, popatre approved these changes
Much improved, well done!

2022-02-20 14:49 UTC, merged