added functionality to include comment count
Dantren18/davids-first-project pull request #8
Opened 2022-02-18 16:38 UTC by Dantren18

Added functionality to the GET /api/articles/:article_id endpoint so the response object now includes a comment count. The tests have been updated to reflect this as well.

2022-02-19 18:40 UTC, popatre requested changes

2022-02-19 18:40 UTC, popatre commented on __tests__/app.test.js
> +            expect(Object.keys(body).length).toEqual(8);
There are 12 articles.

2022-02-19 18:40 UTC, popatre commented on models/models.js
> +        INNER JOIN comments
I'd have another look at this choice of INNER JOIN.

You should still get back all the articles. 
At the moment with this join, you will only get back the articles with have comments. 
What if an article doesn't have any comments?

2022-02-20 20:29 UTC, Dantren18 commented on models/models.js
> +        INNER JOIN comments
Thanks for the feedback! I've made the change, and also added a test for this case.

2022-02-20 20:42 UTC, merged